let token=localStorage.getItem('alfa_admin_token')||'';let selectedDays=7;const $=id=>document.getElementById(id);
function authFetch(url,opt={}){opt.headers={...(opt.headers||{}),Authorization:`Bearer ${token}`,'Content-Type':'application/json'};return fetch(url,opt).then(async r=>{const d=await r.json().catch(()=>({}));if(r.status===401){logout();throw new Error('AUTH')}if(!r.ok)throw new Error(d.error||'Request failed');return d})}
function showApp(){ $('loginView').classList.add('hidden');$('appView').classList.remove('hidden');load();}
function logout(){localStorage.removeItem('alfa_admin_token');token='';$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}
if(token)showApp();
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Login failed');token=d.token;localStorage.setItem('alfa_admin_token',token);showApp()}catch(err){$('loginError').textContent=err.message==='ADMIN_SECRETS_NOT_CONFIGURED'?'Admin secrets are not configured.': 'Invalid admin credentials.'}});
$('logout').onclick=logout;
document.querySelectorAll('.plan').forEach(b=>b.onclick=()=>{document.querySelectorAll('.plan').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedDays=Number(b.dataset.days)});
$('generate').onclick=async()=>{try{const d=await authFetch('/api/admin/licenses/generate',{method:'POST',body:JSON.stringify({days:selectedDays,maxDevices:Number($('maxDevices').value)})});$('keyText').textContent=d.license.key;$('newKey').classList.remove('hidden');await load()}catch(e){alert(e.message)}};
$('copyKey').onclick=()=>navigator.clipboard.writeText($('keyText').textContent);
$('refresh').onclick=load;
async function load(){try{const d=await authFetch('/api/admin/licenses');const list=d.licenses||[];$('allCount').textContent=list.length;$('activeCount').textContent=list.filter(x=>x.status==='active').length;$('unusedCount').textContent=list.filter(x=>x.status==='unused').length;$('deadCount').textContent=list.filter(x=>['expired','revoked'].includes(x.status)).length;$('rows').innerHTML=list.map(x=>`<tr><td><code>${x.maskedKey}</code></td><td>${x.planDays} DAYS</td><td><span class="status ${x.status}">${x.status.toUpperCase()}</span></td><td>${x.expiresAt?new Date(x.expiresAt).toLocaleString():'ON ACTIVATION'}</td><td>${x.activations||0}/${x.maxDevices||1}</td><td>${x.status!=='revoked'&&x.status!=='expired'?`<button class="revoke" data-id="${x.id}">REVOKE</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">No licenses yet.</td></tr>';$('rows').querySelectorAll('.revoke').forEach(b=>b.onclick=async()=>{if(!confirm('Revoke this license?'))return;await authFetch('/api/admin/licenses/'+b.dataset.id+'/revoke',{method:'POST'});load()});$('serverStatus').textContent='CONNECTED'}catch(e){$('serverStatus').textContent='OFFLINE'}}
